using System;

namespace SKYNET.Hook.Types
{
	[Flags]
	public enum LoadLibraryFlags
	{
		DONT_RESOLVE_DLL_REFERENCES = 0x1,
		LOAD_IGNORE_CODE_AUTHZ_LEVEL = 0x10,
		LOAD_LIBRARY_AS_DATAFILE = 0x2,
		LOAD_LIBRARY_AS_DATAFILE_EXCLUSIVE = 0x40,
		LOAD_LIBRARY_AS_IMAGE_RESOURCE = 0x200,
		LOAD_LIBRARY_SEARCH_DEFAULT_DIRS = 0x1000,
		LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR = 0x100,
		LOAD_LIBRARY_SEARCH_SYSTEM32 = 0x800,
		LOAD_LIBRARY_SEARCH_USER_DIRS = 0x400,
		LOAD_WITH_ALTERED_SEARCH_PATH = 0x8
	}
}
